import React, { useEffect, useMemo, useState } from 'react';
import { getAdminUsers } from '../services/userService';
import { archiveAdminVehicle, createAdminVehicle, getAdminVehicles, setAdminVehicleStatus, updateAdminVehicle } from '../services/vehicleService';

const blank = { ownerId: '', registrationNumber: '', vehicleType: 'CAR', brand: '', model: '', color: '', active: true };
const message = (error) => error.response?.data?.message || 'The vehicle operation failed.';

export default function AdminVehicles() {
  const [vehicles, setVehicles] = useState([]); const [users, setUsers] = useState([]); const [loading, setLoading] = useState(true);
  const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [type, setType] = useState('ALL');
  const [editing, setEditing] = useState(null); const [form, setForm] = useState(blank); const [saving, setSaving] = useState(false);
  const [confirming, setConfirming] = useState(null); const [viewing, setViewing] = useState(null);
  const load = async () => { setLoading(true); setError(''); try { const [vehicleRes, userRes] = await Promise.all([getAdminVehicles(), getAdminUsers()]); setVehicles(Array.isArray(vehicleRes.data) ? vehicleRes.data : []); setUsers((Array.isArray(userRes.data) ? userRes.data : []).filter((u) => !u.archived)); } catch (e) { setError(message(e)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => vehicles.filter((v) => (type === 'ALL' || v.vehicleType === type) && (!search || `${v.registrationNumber} ${v.ownerName} ${v.ownerEmail}`.toLowerCase().includes(search.toLowerCase()))), [vehicles, search, type]);
  const open = (vehicle = null) => { setEditing(vehicle); setError(''); setForm(vehicle ? { ownerId: vehicle.ownerId, registrationNumber: vehicle.registrationNumber, vehicleType: vehicle.vehicleType, brand: vehicle.brand || '', model: vehicle.model || '', color: vehicle.color || '', active: vehicle.active } : blank); };
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { if (editing?.id) await updateAdminVehicle(editing.id, form); else await createAdminVehicle(form); setEditing(null); setForm(blank); await load(); } catch (e) { setError(message(e)); } finally { setSaving(false); } };
  const toggle = async (vehicle) => { try { await setAdminVehicleStatus(vehicle.id, !vehicle.active); await load(); } catch (e) { setError(message(e)); } };
  const archive = async () => { if (!confirming) return; setSaving(true); try { await archiveAdminVehicle(confirming.id); setConfirming(null); await load(); } catch (e) { setError(message(e)); } finally { setSaving(false); } };
  return <div className="container admin-page">
    <div className="admin-compact-page-head admin-module-head"><div><span className="admin-module-eyebrow">Vehicle registry</span><h2>Vehicle Management</h2><p>Manage user-owned vehicles linked from bookings.</p></div><button className="btn" onClick={() => open({})}>+ Add Vehicle</button></div>
    <div className="admin-module-stats"><article><span>All Vehicles</span><strong>{vehicles.length}</strong><small>Registered records</small></article><article className="is-green"><span>Active</span><strong>{vehicles.filter(v=>v.active).length}</strong><small>Ready for booking</small></article><article className="is-purple"><span>Vehicle Owners</span><strong>{new Set(vehicles.map(v=>v.ownerId)).size}</strong><small>Linked users</small></article></div>
    <section className="card users-card"><div className="users-filters"><div className="form-group"><label>Search registration or owner</label><input value={search} onChange={(e) => setSearch(e.target.value)} /></div><div className="form-group"><label>Vehicle Type</label><select value={type} onChange={(e) => setType(e.target.value)}><option value="ALL">All</option>{['TWO_WHEELER','CAR','SUV','COMMERCIAL'].map((x) => <option key={x}>{x}</option>)}</select></div></div></section>
    <section className="card users-card">{error && <div className="error-text">{error}</div>}{loading ? <div className="empty-state">Loading vehicles...</div> : !visible.length ? <div className="empty-state">No vehicles found.</div> : <div className="dashboard-table-wrap"><table className="dashboard-table"><thead><tr><th>ID</th><th>Registration</th><th>Owner</th><th>Type</th><th>Brand / Model</th><th>Color</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map((v) => <tr key={v.id}><td>{v.id}</td><td><strong>{v.registrationNumber}</strong></td><td>{v.ownerName}<small>{v.ownerEmail}</small></td><td>{v.vehicleType}</td><td>{[v.brand,v.model].filter(Boolean).join(' ') || 'N/A'}</td><td>{v.color || 'N/A'}</td><td><span className={`badge ${v.active ? 'badge-active' : 'badge-cancelled'}`}>{v.active ? 'ACTIVE' : 'INACTIVE'}</span></td><td><div className="manage-slots-actions"><button className="btn btn-secondary" onClick={() => setViewing(v)}>View</button><button className="btn btn-secondary" onClick={() => open(v)}>Edit</button><button className="btn btn-secondary" onClick={() => toggle(v)}>{v.active ? 'Deactivate' : 'Activate'}</button><button className="btn btn-danger" onClick={() => setConfirming(v)}>Archive</button></div></td></tr>)}</tbody></table></div>}</section>
    {editing !== null && <div className="modal-backdrop"><form className="modal-card" onSubmit={submit}><div className="dashboard-section-head"><h3>{editing?.id ? 'Edit Vehicle' : 'Add Vehicle'}</h3><button type="button" className="modal-close" onClick={() => setEditing(null)}>×</button></div><div className="profile-form-grid"><div className="form-group"><label>Owner</label><select required value={form.ownerId} onChange={(e) => setForm({...form, ownerId: e.target.value})}><option value="">Select owner</option>{users.map((u) => <option key={u.id} value={u.id}>{u.name} — {u.email}</option>)}</select></div><div className="form-group"><label>Registration Number</label><input required value={form.registrationNumber} onChange={(e) => setForm({...form, registrationNumber: e.target.value})} /></div><div className="form-group"><label>Vehicle Type</label><select value={form.vehicleType} onChange={(e) => setForm({...form, vehicleType: e.target.value})}>{['TWO_WHEELER','CAR','SUV','COMMERCIAL'].map((x) => <option key={x}>{x}</option>)}</select></div>{['brand','model','color'].map((field) => <div className="form-group" key={field}><label>{field[0].toUpperCase()+field.slice(1)}</label><input value={form[field]} onChange={(e) => setForm({...form, [field]: e.target.value})} /></div>)}</div>{error && <div className="error-text">{error}</div>}<div className="manage-slots-actions"><button type="button" className="btn btn-secondary" onClick={() => setEditing(null)}>Cancel</button><button className="btn" disabled={saving}>{saving ? 'Saving...' : 'Save Vehicle'}</button></div></form></div>}
    {viewing && <div className="modal-backdrop"><div className="modal-card"><div className="dashboard-section-head"><h3>Vehicle Details</h3><button className="modal-close" onClick={() => setViewing(null)}>×</button></div><div className="booking-details-grid"><div><strong>Registration:</strong> {viewing.registrationNumber}</div><div><strong>Owner:</strong> {viewing.ownerName}</div><div><strong>Email:</strong> {viewing.ownerEmail}</div><div><strong>Type:</strong> {viewing.vehicleType}</div><div><strong>Brand:</strong> {viewing.brand || 'N/A'}</div><div><strong>Model:</strong> {viewing.model || 'N/A'}</div><div><strong>Color:</strong> {viewing.color || 'N/A'}</div></div></div></div>}
    {confirming && <div className="modal-backdrop"><div className="modal-card confirm-card"><h3>Archive Vehicle</h3><p>Archive {confirming.registrationNumber}? Historical booking text remains unchanged.</p><div className="manage-slots-actions"><button className="btn btn-secondary" onClick={() => setConfirming(null)}>Cancel</button><button className="btn btn-danger" disabled={saving} onClick={archive}>{saving ? 'Archiving...' : 'Archive'}</button></div></div></div>}
  </div>;
}
